#define LONG_WORDS_FILENAME "long_words.txt"
#define NORMAL_WORDS_FILENAME "normal_words.txt"
#define HARD_WORDS_FILENAME "hard_words.txt"
#define USERINFO_FILENAME "userInfo.bin"
#define GAMES_LOG_FILENAME "gamesLog.bin"